const sr = {
  header: {
    search: 'Pretraži proizvode...',
    login: 'Prijavi se',
    register: 'Registruj se',
    cart: 'Korpa',
    wishlist: 'Lista želja',
    account: 'Moj nalog',
    orders: 'Moje narudžbine',
  },
  menu: {
    all: 'Sve kategorije',
    supermarket: 'Supermarket',
    homeGarden: 'Dom i bašta',
    electronics: 'Tehnika',
    computers: 'Računari',
    sports: 'Sport i rekreacija',
    baby: 'Beba i deca',
    fashion: 'Moda',
    automotive: 'Auto-moto',
    tools: 'Alati i majstorstvo',
    office: 'Kancelarija',
    beauty: 'Lepota i zdravlje',
    toys: 'Igračke i hobiji',
  },
  home: {
    heroBtnShop: 'Kupuj odmah',
    heroBtnDiscover: 'Otkrij ponudu',
    featuredDeals: 'Nedeljne akcije',
    newArrivals: 'Novo u ponudi',
    topCategories: 'Popularne kategorije',
    viewAll: 'Pogledaj sve',
    addToCart: 'Dodaj u korpu',
    infoDelivery: 'Besplatna dostava',
    infoDeliveryDesc: 'Za narudžbine iznad 3.000 RSD',
    infoSecure: 'Sigurna kupovina',
    infoSecureDesc: 'SSL zaštita i provjereni prodavci',
    infoReturn: 'Povrat do 30 dana',
    infoReturnDesc: 'Jednostavan povrat robe bez pitanja',
    infoSupport: 'Podrška 24/7',
    infoSupportDesc: 'Uvijek smo tu za vas',
    subscribeTitle: 'Prijavite se na newsletter',
    subscribeDesc: 'Budite prvi koji saznaje za akcije i ekskluzivne ponude',
    subscribePlaceholder: 'Unesite e-mail adresu',
    subscribeBtn: 'Prijavite se',
  },
  footer: {
    about: 'O nama',
    contact: 'Kontakt',
    careers: 'Karijere',
    press: 'Press',
    help: 'Pomoć',
    faq: 'FAQ',
    shipping: 'Dostava',
    returns: 'Povrat',
    privacy: 'Politika privatnosti',
    terms: 'Uslovi korišćenja',
    followUs: 'Pratite nas',
    copyright: '© 2024 Bazzar.rs - Sva prava zadržana',
    paymentMethods: 'Načini plaćanja',
  },
};

export default sr;
